"""Re-emit the two supplied lockups with their wordmarks as OUTLINE PATHS.

The supplied files set the wordmark as <text font-family="'Barlow Condensed'...">
and embed no font. An SVG loaded as an <img>, used as a favicon, or opened in
Canva / Illustrator / Figma is its own document and cannot borrow a font from the
page around it — so anywhere Barlow Condensed is not installed, the letters
reshape. Outlines make the file say the same thing everywhere.

Geometry is taken verbatim from the supplied files so the result is the same
drawing, not a redraw:
  SHEDPRO  x=68  baseline y=34  size 26  letter-spacing 0.5  weight 900
           "SHED" in the theme colour, "PRO" in brand blue (the tspan)
  STUDIO   x=69  baseline y=48  size 13  letter-spacing 4.6  weight 700
SVG letter-spacing is in USER UNITS; Text2Path takes tracking in em, so each is
divided by its own font-size.
"""
from txt2path import Text2Path

MARK = '''  <g stroke="#2BB5E8" stroke-width="3" stroke-linecap="round" stroke-linejoin="round">
    <path d="M8 27 L26 15 L44 27"/>
    <path d="M11 27 V43 H41 V27"/>
  </g>
  <g stroke="#F8921E" stroke-width="2.2" stroke-linecap="round">
    <path d="M8 50 H44"/><path d="M8 47.5 V52.5"/><path d="M44 47.5 V52.5"/>
    <path d="M51 15 V43"/><path d="M48.5 15 H53.5"/><path d="M48.5 43 H53.5"/>
  </g>'''

t900 = Text2Path('BarlowCondensed-900.ttf')
t700 = Text2Path('BarlowCondensed-700.ttf')

SIZE_W, TRACK_W, X_W, Y_W = 26, 0.5, 68, 34
SIZE_S, TRACK_S, X_S, Y_S = 13, 4.6, 69, 48

# "SHED" then "PRO", advanced by SHED's own width so the pair sits exactly as
# the single <text> + <tspan> did.
shed, _   = t900.path('SHED', SIZE_W, TRACK_W/SIZE_W, X_W, Y_W)
w_shed    = t900.width('SHED', SIZE_W, TRACK_W/SIZE_W) + TRACK_W   # + the gap to the next glyph
pro, _    = t900.path('PRO',  SIZE_W, TRACK_W/SIZE_W, X_W + w_shed, Y_W)
studio, _ = t700.path('STUDIO', SIZE_S, TRACK_S/SIZE_S, X_S, Y_S)

def build(shed_fill):
    # viewBox is trimmed to the PAINTED artwork (measured by rendering, so
    # stroke width and line caps are included), plus a 2-unit margin. It used
    # to be 0 0 260 60 — a box left over from when the wordmark was <text> —
    # whose art stopped at x=157, leaving 103 units of dead space on the right.
    # Anything centring the image centred that box, which pushed the visible
    # logo 18% of its own width to the left.
    return f'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="4.5 11.5 154.6 44.1" width="464" height="132" fill="none">
  <!-- Wordmark is OUTLINES, not <text>: the file names no font, so it renders
       identically in a browser, in an <img>, as a favicon, and in Canva or
       Illustrator. Regenerated by logo/outline_lockup.py from Barlow Condensed
       900 (SHEDPRO) and 700 (STUDIO) at the geometry of the original. -->
{MARK}
  <g fill="{shed_fill}"><path d="{shed}"/></g>
  <g fill="#2BB5E8"><path d="{pro}"/></g>
  <g fill="#F8921E"><path d="{studio}"/></g>
</svg>
'''

open('out-lockup-dark-bg.svg','w').write(build('#FFFFFF'))
open('out-lockup-light-bg.svg','w').write(build('#14181C'))
print('SHED width  :', round(t900.width('SHED', SIZE_W, TRACK_W/SIZE_W), 2))
print('SHEDPRO end :', round(X_W + w_shed + t900.width('PRO', SIZE_W, TRACK_W/SIZE_W), 2))
print('STUDIO end  :', round(X_S + t700.width('STUDIO', SIZE_S, TRACK_S/SIZE_S), 2))
print('wrote out-lockup-dark-bg.svg, out-lockup-light-bg.svg')
